USE [db_ac5777_mkkprod1]
GO
/****** Object:  Table [dbo].[TMKK_ASISTENCIA]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_ASISTENCIA](
	[CASI_ID_ASISTENCIA] [int] IDENTITY(1,1) NOT NULL,
	[SASI_NOMBRE] [varchar](500) NULL,
	[SASI_ABREVIATURA] [varchar](10) NULL,
	[FASI_DESCUENTA] [char](1) NULL,
	[FASI_ESTADO] [char](1) NULL,
	[SASI_VISTA] [varchar](100) NULL,
	[SASI_COLOR] [varchar](100) NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CASI_ID_ASISTENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_DOCUMENTO]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_DOCUMENTO](
	[CDCN_ID_DOCUMENTO] [int] IDENTITY(1,1) NOT NULL,
	[SDCN_TITULO] [varchar](200) NULL,
	[SDCN_ABREVIATURA] [varchar](10) NULL,
	[SDCN_DESCRIPCION] [varchar](500) NULL,
	[FDCN_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CDCN_ID_DOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_LLAMADA]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_LLAMADA](
	[CLLM_ID_LLAMADA] [int] IDENTITY(1,1) NOT NULL,
	[CLLM_ID_USUARIO] [int] NULL,
	[SLLM_TELEFONO] [varchar](20) NOT NULL,
	[SVEN_TIPO_VENTA] [int] NULL,
	[SLLM_TIPIFICACION_NIVEL_1] [varchar](100) NULL,
	[SLLM_TIPIFICACION_NIVEL_2] [varchar](100) NULL,
	[SLLM_OBSERVACIONES] [varchar](100) NULL,
	[FLLM_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CLLM_ID_LLAMADA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_MENU]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_MENU](
	[CMNU_ID_MENU] [int] IDENTITY(1,1) NOT NULL,
	[CSIT_ID_SISTEMA] [int] NOT NULL,
	[CMNU_MENU_PADRE] [int] NULL,
	[SMNU_NOMBRE] [varchar](100) NOT NULL,
	[SMNU_RUTA_VISUAL] [varchar](255) NULL,
	[SMNU_ICONO] [varchar](50) NULL,
	[NMNU_ORDEN] [int] NULL,
	[FMNU_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CMNU_ID_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_OPERADOR]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_OPERADOR](
	[COPE_ID_OPERADOR] [smallint] NOT NULL,
	[SOPE_NOMBRE] [varchar](60) NULL,
	[SOPE_NOM_CORTO] [varchar](30) NULL,
	[FOPE_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
	[SOPE_ID_EXTERNO] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[COPE_ID_OPERADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_PERFIL]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_PERFIL](
	[CPFL_ID_PERFIL] [int] IDENTITY(1,1) NOT NULL,
	[CSIT_ID_SISTEMA] [int] NOT NULL,
	[SPFL_NOMBRE] [varchar](50) NOT NULL,
	[SPFL_DESCRIPCION] [varchar](255) NULL,
	[FPFL_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPFL_ID_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_PERFIL_MENU]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_PERFIL_MENU](
	[CPFL_ID_PERFIL] [int] NOT NULL,
	[CMNU_ID_MENU] [int] NOT NULL,
	[FRLM_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPFL_ID_PERFIL] ASC,
	[CMNU_ID_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_PERL_DOCUMENTO]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_PERL_DOCUMENTO](
	[CPEL_ID_PERSONAL] [int] NOT NULL,
	[CDCN_ID_DOCUMENTO] [int] NOT NULL,
	[SDCN_UBICACION] [varchar](300) NULL,
	[FDCN_EST_DOCUMENTO] [char](1) NULL,
	[FDCN_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPEL_ID_PERSONAL] ASC,
	[CDCN_ID_DOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_PERSONAL]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_PERSONAL](
	[CPEL_ID_PERSONAL] [int] IDENTITY(1,1) NOT NULL,
	[CPER_ID_PERSONA] [int] NOT NULL,
	[SVEN_TIPO_VENTA] [int] NULL,
	[CUSU_ID_USUARIO] [int] NULL,
	[CPFL_ID_PERFIL] [int] NOT NULL,
	[CPEl_ID_HUELLERO] [varchar](16) NULL,
	[CPEl_ID_VICIDIAL] [varchar](16) NULL,
	[CPEl_ID_MANTRA] [varchar](16) NULL,
	[FPEl_INICIO_CONTRATO] [datetime] NULL,
	[FPEl_FIN_CONTRATO] [datetime] NULL,
	[FPEl_INGRESO] [datetime] NULL,
	[FPEl_ESTADO] [char](1) NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CPEL_ID_PERSONAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_PLAN]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_PLAN](
	[CPLN_ID_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[SPLN_NOMBRE] [varchar](100) NOT NULL,
	[SPLN_DES_PLAN] [varchar](100) NOT NULL,
	[NPLN_VALOR_PLAN] [decimal](14, 2) NOT NULL,
	[FPLN_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPLN_ID_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_SISTEMA]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_SISTEMA](
	[CSIT_ID_SISTEMA] [int] IDENTITY(1,1) NOT NULL,
	[SSIT_NOMBRE] [varchar](100) NOT NULL,
	[SSIT_DESCRIPCION] [varchar](255) NULL,
	[SSIT_URL_ACCESO] [varchar](255) NULL,
	[SIT_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CSIT_ID_SISTEMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_TIP_DOC_IDENTIDAD]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_TIP_DOC_IDENTIDAD](
	[CTDI_ID_DOCUMENTO] [tinyint] NOT NULL,
	[STDI_NOMBRE] [varchar](40) NULL,
	[STDI_ABREVIATURA] [varchar](20) NULL,
	[FTDI_TIP_PERSONA] [char](1) NULL,
	[FTDI_TIP_CONTENIDO] [char](1) NULL,
	[NTDI_MIN_LONGITUD] [tinyint] NULL,
	[NTDI_MAX_LONGITUD] [tinyint] NULL,
	[FTDI_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CTDI_ID_DOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_TIP_VALOR]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_TIP_VALOR](
	[CTPV_COD_TIP_VALOR] [varchar](20) NOT NULL,
	[CTPV_TIP_VALOR] [varchar](8) NOT NULL,
	[STPV_DES_TIP_VALOR_1] [varchar](128) NULL,
	[STPV_DES_TIP_VALOR_2] [varchar](128) NULL,
	[STPV_DES_TIP_VALOR_3] [varchar](128) NULL,
	[FTPV_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CTPV_COD_TIP_VALOR] ASC,
	[CTPV_TIP_VALOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_USUARIO]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_USUARIO](
	[CUSU_ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[CPER_ID_PERSONA] [int] NOT NULL,
	[SUSU_USERNAME] [varchar](50) NOT NULL,
	[SUSU_PASSWORD_HASH] [varchar](255) NOT NULL,
	[FUSU_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSU_ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_USUARIO_EXCEPCION_MENU]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU](
	[CUSU_ID_USUARIO] [int] NOT NULL,
	[CMNU_ID_MENU] [int] NOT NULL,
	[FUME_ESTADO] [char](1) NULL,
	[DUSR_FECHA_ASIGNACION] [datetime] NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSU_ID_USUARIO] ASC,
	[CMNU_ID_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_USUARIO_PERFIL]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_USUARIO_PERFIL](
	[CUSU_ID_USUARIO] [int] NOT NULL,
	[CPFL_ID_PERFIL] [int] NOT NULL,
	[DUSR_FECHA_ASIGNACION] [datetime] NULL,
	[FUSR_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSU_ID_USUARIO] ASC,
	[CPFL_ID_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_VENTA]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_VENTA](
	[CVEN_ID_VENTA] [int] IDENTITY(1,1) NOT NULL,
	[CVEN_ID_LLAMADA] [int] NULL,
	[CVEN_ID_CLIENTE] [int] NULL,
	[CPLN_ID_CODIGO] [int] NULL,
	[DVEN_FECHA_REGISTRO] [datetime] NULL,
	[SVEN_TIPO_VENTA] [varchar](50) NULL,
	[SUBIGEO] [varchar](150) NULL,
	[SDIRECCION_EXACTA] [varchar](250) NULL,
	[SREFERENCIA] [varchar](250) NULL,
	[SNUM_ORDEN] [varchar](50) NULL,
	[FVEN_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CVEN_ID_VENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_VENTA_PORTABILIDAD]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_VENTA_PORTABILIDAD](
	[CVEN_ID_VENTA] [int] NOT NULL,
	[SCELULAR_MIGRAR] [varchar](20) NOT NULL,
	[SOPERADOR_PROCEDENCIA] [varchar](50) NULL,
	[SMODALIDAD] [varchar](50) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CVEN_ID_VENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TMKK_VENTA_POST_POST]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMKK_VENTA_POST_POST](
	[CVEN_ID_VENTA] [int] NOT NULL,
	[SCELULAR_MIGRAR] [varchar](20) NOT NULL,
	[SPLAN_ANTERIOR] [varchar](100) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CVEN_ID_VENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TPLS_PERSONA]    Script Date: 6/10/2026 23:10:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TPLS_PERSONA](
	[CPER_ID_PERSONA] [int] IDENTITY(1,1) NOT NULL,
	[FPER_TIP_PERSONA] [char](1) NULL,
	[FPER_TIP_DOC_IDENTIDAD] [char](1) NULL,
	[SPER_NRO_DOC_IDENTIDAD] [varchar](16) NULL,
	[SPER_RAZ_SOCIAL] [varchar](128) NULL,
	[SPER_NOMBRE] [varchar](64) NULL,
	[SPER_SEG_NOMBRE] [varchar](32) NULL,
	[SPER_APE_PATERNO] [varchar](32) NULL,
	[SPER_APE_MATERNO] [varchar](32) NULL,
	[SPER_APE_CASADA] [varchar](32) NULL,
	[FPER_TIP_SEXO] [char](1) NULL,
	[SPER_FEC_NACIMIENTO] [date] NULL,
	[SPER_NACIONALIDAD] [varchar](30) NULL,
	[SPER_UBI_NACIMIENTO] [varchar](8) NULL,
	[NPER_EDAD] [tinyint] NULL,
	[FPER_TIP_EST_CIVIL] [char](1) NULL,
	[SPER_TELEFONO] [varchar](16) NULL,
	[SPER_CELULAR] [varchar](16) NULL,
	[SPER_COR_PERSONAL] [varchar](100) NULL,
	[SPER_COR_LABORAL] [varchar](100) NULL,
	[SPER_COR_EMPRESA] [varchar](100) NULL,
	[FPER_ESTADO] [char](1) NULL,
	[AUD_INS_FEC] [datetime] NULL,
	[AUD_INS_USER] [varchar](16) NULL,
	[AUD_UPD_FEC] [datetime] NULL,
	[AUD_UPD_USER] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPER_ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TMKK_ASISTENCIA] ON 
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (1, N'PUNTUAL', N'P', N'N', N'V', N'PUNTUAL', N'PUNTUAL', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (2, N'TARDANZA', N'T', N'N', N'V', N'TARDANZA', N'TARDANZA', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (3, N'FALTA INJUSTIFICADA', N'FI', N'S', N'V', N'FALTA INJUSTIFICADA', N'FALTA INJUSTIFICADA', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (4, N'FALTA JUSTIFICADA', N'FJ', N'S', N'V', N'FALTA JUSTIFICADA', N'FALTA JUSTIFICADA', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (5, N'LICENCIA MATERNIDAD', N'LM', N'N', N'V', N'LICENCIA MATERNIDAD', N'LICENCIA MATERNIDAD', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (6, N'LICENCIA PATERNIDAD', N'LP', N'N', N'V', N'LICENCIA PATERNIDAD', N'LICENCIA PATERNIDAD', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (7, N'DESCANSO MEDICO', N'DM', N'N', N'V', N'DESCANSO MEDICO', N'DESCANSO MEDICO', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (8, N'DESCANSO SEMANAL', N'DS', N'N', N'V', N'DESCANSO SEMANAL', N'DESCANSO SEMANAL', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (9, N'OBSERVADO', N'OB', N'S', N'V', N'OBSERVADO', N'OBSERVADO', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[TMKK_ASISTENCIA] ([CASI_ID_ASISTENCIA], [SASI_NOMBRE], [SASI_ABREVIATURA], [FASI_DESCUENTA], [FASI_ESTADO], [SASI_VISTA], [SASI_COLOR], [AUD_INS_USER], [AUD_INS_FEC], [AUD_UPD_USER], [AUD_UPD_FEC]) VALUES (10, N'VACACIONES', N'V', N'N', N'V', N'VACACIONES', N'VACACIONES', N'AIW_SISTEMAS', CAST(N'2026-08-05T21:35:52.730' AS DateTime), NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[TMKK_ASISTENCIA] OFF
GO
INSERT [dbo].[TMKK_OPERADOR] ([COPE_ID_OPERADOR], [SOPE_NOMBRE], [SOPE_NOM_CORTO], [FOPE_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER], [SOPE_ID_EXTERNO]) VALUES (1, N'CLARO', NULL, N'V', CAST(N'2026-08-05T21:30:58.547' AS DateTime), N'AIW_SISTEMAS', NULL, NULL, NULL)
GO
INSERT [dbo].[TMKK_OPERADOR] ([COPE_ID_OPERADOR], [SOPE_NOMBRE], [SOPE_NOM_CORTO], [FOPE_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER], [SOPE_ID_EXTERNO]) VALUES (2, N'MOVISTAR', NULL, N'V', CAST(N'2026-08-05T21:30:58.547' AS DateTime), N'AIW_SISTEMAS', NULL, NULL, NULL)
GO
INSERT [dbo].[TMKK_OPERADOR] ([COPE_ID_OPERADOR], [SOPE_NOMBRE], [SOPE_NOM_CORTO], [FOPE_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER], [SOPE_ID_EXTERNO]) VALUES (3, N'ENTEL', NULL, N'V', CAST(N'2026-08-05T21:30:58.547' AS DateTime), N'AIW_SISTEMAS', NULL, NULL, NULL)
GO
INSERT [dbo].[TMKK_OPERADOR] ([COPE_ID_OPERADOR], [SOPE_NOMBRE], [SOPE_NOM_CORTO], [FOPE_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER], [SOPE_ID_EXTERNO]) VALUES (4, N'BITEL', NULL, N'V', CAST(N'2026-08-05T21:30:58.547' AS DateTime), N'AIW_SISTEMAS', NULL, NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (1, N'DOCUMENTO NACIONAL DE IDENTIDAD', N'DNI', N'1', N'N', 8, 8, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (2, N'REGISTRO ÚNICO DEL CONTRIBUYENTE', N'RUC', N'2', N'N', 11, 11, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (3, N'CARNET DE EXTRANJERIA', N'CAR. EXTRANJERIA', N'1', N'A', 9, 9, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (4, N'CARNET IDENTIDAD PERSONAL', NULL, NULL, NULL, NULL, NULL, N'A', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (5, N'PERMISO TEMPORAL DE PERMANENCIA', N'PTP', N'1', N'A', 9, 9, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (6, N'PASAPORTE', N'PASAPORTE', N'1', N'A', 16, 16, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (7, N'CARNET FUERZAS POLICIALES', NULL, NULL, NULL, NULL, NULL, N'A', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (8, N'CARNET FUERZAS ARMADAS', NULL, NULL, NULL, NULL, NULL, N'A', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_DOC_IDENTIDAD] ([CTDI_ID_DOCUMENTO], [STDI_NOMBRE], [STDI_ABREVIATURA], [FTDI_TIP_PERSONA], [FTDI_TIP_CONTENIDO], [NTDI_MIN_LONGITUD], [NTDI_MAX_LONGITUD], [FTDI_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (9, N'CODIGO DE RECIEN NACIDO', N'COD. RECIEN NACIDO', N'1', N'N', 8, 8, N'V', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS', CAST(N'2026-08-05T21:30:58.540' AS DateTime), N'AIW_SISTEMAS')
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'1', N'ACTIVO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'2', N'CAÍDA', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'3', N'PROCESAMIENTO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'4', N'CANCELADO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'5', N'PENDIENTE', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'6', N'One way block', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'7', N'NUEVO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'8', N'CANCELADO-ONE WAY BLOCK', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO', N'9', N'ACTIVO-TWO WAY BLOCK', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'1', N'ACTIVADO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'2', N'CANCELADO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'3', N'PENDIENTE', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'4', N'CAIDO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'6', N'PROCESAMIENTO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_ESTADO_VENTA', N'7', N'OBSERVACION', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'1', N'Espera 90 días (oferta activa)', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'11', N'Solicitud postpago existente', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'2', N'Ya cuenta con plan activo', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'3', N'Falla en lectura de contrato', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'4', N'Migración reciente a prepago', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'5', N'Upgrade insuficiente', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'6', N'Datos erróneos', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'7', N'Línea cancelada', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'8', N'Info cliente no coincide', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_MOTIVO_CAIDA', N'9', N'No aplica', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_PRUEBA', N'P', N'PRUEBA_2', N'', N'', N'V', CAST(N'2026-08-14T20:40:39.827' AS DateTime), N'ADMIN', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIP_PRUEBA', N'T', N'PRUEBA', N'', N'', N'V', NULL, N'ADMIN', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_EST_DOCUMENTO', N'1', N'PENDIENTE', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_EST_DOCUMENTO', N'2', N'CARGADO', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_VENTA', N'1', N'PRE A POST', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_VENTA', N'2', N'PORTABILIDAD', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_VENTA', N'3', N'POST A POST', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
INSERT [dbo].[TMKK_TIP_VALOR] ([CTPV_COD_TIP_VALOR], [CTPV_TIP_VALOR], [STPV_DES_TIP_VALOR_1], [STPV_DES_TIP_VALOR_2], [STPV_DES_TIP_VALOR_3], [FTPV_ESTADO], [AUD_INS_FEC], [AUD_INS_USER], [AUD_UPD_FEC], [AUD_UPD_USER]) VALUES (N'TIPO_VENTA', N'4', N'LINEA NUEVA', NULL, NULL, N'V', CAST(N'2026-08-05T21:30:58.527' AS DateTime), N'AIW_SISTEMAS', NULL, NULL)
GO
/****** Object:  Index [UQ__TMKK_USU__30984F73448A55B2]    Script Date: 6/10/2026 23:10:54 ******/
ALTER TABLE [dbo].[TMKK_USUARIO] ADD UNIQUE NONCLUSTERED 
(
	[CPER_ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__TMKK_USU__97F27CDFBCF5FD48]    Script Date: 6/10/2026 23:10:54 ******/
ALTER TABLE [dbo].[TMKK_USUARIO] ADD UNIQUE NONCLUSTERED 
(
	[SUSU_USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMKK_ASISTENCIA] ADD  DEFAULT ('V') FOR [FASI_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_DOCUMENTO] ADD  DEFAULT ('V') FOR [FDCN_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_LLAMADA] ADD  DEFAULT ('V') FOR [FLLM_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_MENU] ADD  DEFAULT ((0)) FOR [NMNU_ORDEN]
GO
ALTER TABLE [dbo].[TMKK_MENU] ADD  DEFAULT ('V') FOR [FMNU_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_OPERADOR] ADD  DEFAULT ('V') FOR [FOPE_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_PERFIL] ADD  DEFAULT ('V') FOR [FPFL_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_PERFIL_MENU] ADD  DEFAULT ('V') FOR [FRLM_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_PLAN] ADD  DEFAULT ('V') FOR [FPLN_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_SISTEMA] ADD  DEFAULT ('1') FOR [SIT_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_TIP_DOC_IDENTIDAD] ADD  DEFAULT ('V') FOR [FTDI_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_TIP_VALOR] ADD  DEFAULT ('V') FOR [FTPV_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_TIP_VALOR] ADD  CONSTRAINT [DF_TMKK_TIP_VALOR_AUD_INS_FEC]  DEFAULT (getdate()) FOR [AUD_INS_FEC]
GO
ALTER TABLE [dbo].[TMKK_USUARIO] ADD  DEFAULT ('V') FOR [FUSU_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU] ADD  DEFAULT ('V') FOR [FUME_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU] ADD  DEFAULT (getdate()) FOR [DUSR_FECHA_ASIGNACION]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL] ADD  DEFAULT (getdate()) FOR [DUSR_FECHA_ASIGNACION]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL] ADD  DEFAULT ('V') FOR [FUSR_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_VENTA] ADD  DEFAULT (getdate()) FOR [DVEN_FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[TMKK_VENTA] ADD  DEFAULT ('V') FOR [FVEN_ESTADO]
GO
ALTER TABLE [dbo].[TMKK_LLAMADA]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_LLAMADA_TMKK_USUARIO] FOREIGN KEY([CLLM_ID_USUARIO])
REFERENCES [dbo].[TMKK_USUARIO] ([CUSU_ID_USUARIO])
GO
ALTER TABLE [dbo].[TMKK_LLAMADA] CHECK CONSTRAINT [FK_TMKK_LLAMADA_TMKK_USUARIO]
GO
ALTER TABLE [dbo].[TMKK_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_MENU_PADRE] FOREIGN KEY([CMNU_MENU_PADRE])
REFERENCES [dbo].[TMKK_MENU] ([CMNU_ID_MENU])
GO
ALTER TABLE [dbo].[TMKK_MENU] CHECK CONSTRAINT [FK_TMKK_MENU_PADRE]
GO
ALTER TABLE [dbo].[TMKK_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_MENU_SISTEMA] FOREIGN KEY([CSIT_ID_SISTEMA])
REFERENCES [dbo].[TMKK_SISTEMA] ([CSIT_ID_SISTEMA])
GO
ALTER TABLE [dbo].[TMKK_MENU] CHECK CONSTRAINT [FK_TMKK_MENU_SISTEMA]
GO
ALTER TABLE [dbo].[TMKK_PERFIL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PERFIL_SISTEMA] FOREIGN KEY([CSIT_ID_SISTEMA])
REFERENCES [dbo].[TMKK_SISTEMA] ([CSIT_ID_SISTEMA])
GO
ALTER TABLE [dbo].[TMKK_PERFIL] CHECK CONSTRAINT [FK_TMKK_PERFIL_SISTEMA]
GO
ALTER TABLE [dbo].[TMKK_PERFIL_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PM_MENU] FOREIGN KEY([CMNU_ID_MENU])
REFERENCES [dbo].[TMKK_MENU] ([CMNU_ID_MENU])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_PERFIL_MENU] CHECK CONSTRAINT [FK_TMKK_PM_MENU]
GO
ALTER TABLE [dbo].[TMKK_PERFIL_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PM_PERFIL] FOREIGN KEY([CPFL_ID_PERFIL])
REFERENCES [dbo].[TMKK_PERFIL] ([CPFL_ID_PERFIL])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_PERFIL_MENU] CHECK CONSTRAINT [FK_TMKK_PM_PERFIL]
GO
ALTER TABLE [dbo].[TMKK_PERL_DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PD_DOCUMENTO] FOREIGN KEY([CDCN_ID_DOCUMENTO])
REFERENCES [dbo].[TMKK_DOCUMENTO] ([CDCN_ID_DOCUMENTO])
GO
ALTER TABLE [dbo].[TMKK_PERL_DOCUMENTO] CHECK CONSTRAINT [FK_TMKK_PD_DOCUMENTO]
GO
ALTER TABLE [dbo].[TMKK_PERL_DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PD_PERSONAL] FOREIGN KEY([CPEL_ID_PERSONAL])
REFERENCES [dbo].[TMKK_PERSONAL] ([CPEL_ID_PERSONAL])
GO
ALTER TABLE [dbo].[TMKK_PERL_DOCUMENTO] CHECK CONSTRAINT [FK_TMKK_PD_PERSONAL]
GO
ALTER TABLE [dbo].[TMKK_PERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PERSONAL_PERFIL] FOREIGN KEY([CPFL_ID_PERFIL])
REFERENCES [dbo].[TMKK_PERFIL] ([CPFL_ID_PERFIL])
GO
ALTER TABLE [dbo].[TMKK_PERSONAL] CHECK CONSTRAINT [FK_TMKK_PERSONAL_PERFIL]
GO
ALTER TABLE [dbo].[TMKK_PERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PERSONAL_PERSONA] FOREIGN KEY([CPER_ID_PERSONA])
REFERENCES [dbo].[TPLS_PERSONA] ([CPER_ID_PERSONA])
GO
ALTER TABLE [dbo].[TMKK_PERSONAL] CHECK CONSTRAINT [FK_TMKK_PERSONAL_PERSONA]
GO
ALTER TABLE [dbo].[TMKK_PERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_PERSONAL_USUARIO] FOREIGN KEY([CUSU_ID_USUARIO])
REFERENCES [dbo].[TMKK_USUARIO] ([CUSU_ID_USUARIO])
GO
ALTER TABLE [dbo].[TMKK_PERSONAL] CHECK CONSTRAINT [FK_TMKK_PERSONAL_USUARIO]
GO
ALTER TABLE [dbo].[TMKK_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_USUARIO_PERSONA] FOREIGN KEY([CPER_ID_PERSONA])
REFERENCES [dbo].[TPLS_PERSONA] ([CPER_ID_PERSONA])
GO
ALTER TABLE [dbo].[TMKK_USUARIO] CHECK CONSTRAINT [FK_TMKK_USUARIO_PERSONA]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_UEM_MENU] FOREIGN KEY([CMNU_ID_MENU])
REFERENCES [dbo].[TMKK_MENU] ([CMNU_ID_MENU])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU] CHECK CONSTRAINT [FK_TMKK_UEM_MENU]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_UEM_USUARIO] FOREIGN KEY([CUSU_ID_USUARIO])
REFERENCES [dbo].[TMKK_USUARIO] ([CUSU_ID_USUARIO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_USUARIO_EXCEPCION_MENU] CHECK CONSTRAINT [FK_TMKK_UEM_USUARIO]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_UP_PERFIL] FOREIGN KEY([CPFL_ID_PERFIL])
REFERENCES [dbo].[TMKK_PERFIL] ([CPFL_ID_PERFIL])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL] CHECK CONSTRAINT [FK_TMKK_UP_PERFIL]
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_UP_USUARIO] FOREIGN KEY([CUSU_ID_USUARIO])
REFERENCES [dbo].[TMKK_USUARIO] ([CUSU_ID_USUARIO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMKK_USUARIO_PERFIL] CHECK CONSTRAINT [FK_TMKK_UP_USUARIO]
GO
ALTER TABLE [dbo].[TMKK_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_VENTA_LLAMADA] FOREIGN KEY([CVEN_ID_LLAMADA])
REFERENCES [dbo].[TMKK_LLAMADA] ([CLLM_ID_LLAMADA])
GO
ALTER TABLE [dbo].[TMKK_VENTA] CHECK CONSTRAINT [FK_TMKK_VENTA_LLAMADA]
GO
ALTER TABLE [dbo].[TMKK_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_VENTA_PERSONA] FOREIGN KEY([CVEN_ID_CLIENTE])
REFERENCES [dbo].[TPLS_PERSONA] ([CPER_ID_PERSONA])
GO
ALTER TABLE [dbo].[TMKK_VENTA] CHECK CONSTRAINT [FK_TMKK_VENTA_PERSONA]
GO
ALTER TABLE [dbo].[TMKK_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_VENTA_PLAN] FOREIGN KEY([CPLN_ID_CODIGO])
REFERENCES [dbo].[TMKK_PLAN] ([CPLN_ID_CODIGO])
GO
ALTER TABLE [dbo].[TMKK_VENTA] CHECK CONSTRAINT [FK_TMKK_VENTA_PLAN]
GO
ALTER TABLE [dbo].[TMKK_VENTA_PORTABILIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_VPORTA_VENTA] FOREIGN KEY([CVEN_ID_VENTA])
REFERENCES [dbo].[TMKK_VENTA] ([CVEN_ID_VENTA])
GO
ALTER TABLE [dbo].[TMKK_VENTA_PORTABILIDAD] CHECK CONSTRAINT [FK_TMKK_VPORTA_VENTA]
GO
ALTER TABLE [dbo].[TMKK_VENTA_POST_POST]  WITH CHECK ADD  CONSTRAINT [FK_TMKK_VPOSTPOST_VENTA] FOREIGN KEY([CVEN_ID_VENTA])
REFERENCES [dbo].[TMKK_VENTA] ([CVEN_ID_VENTA])
GO
ALTER TABLE [dbo].[TMKK_VENTA_POST_POST] CHECK CONSTRAINT [FK_TMKK_VPOSTPOST_VENTA]
GO
/****** Object:  StoredProcedure [dbo].[PRMKK_CON_BOF_TIP_VALOR]    Script Date: 6/10/2026 23:10:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRMKK_CON_BOF_TIP_VALOR]
@i_TIP_ESTADO VARCHAR(50),
@i_TIP_VALOR VARCHAR(5),
@i_DESCRIPCION VARCHAR(250)
AS 
BEGIN
	
	SELECT 
	CTPV_TIP_VALOR id,
	STPV_DES_TIP_VALOR_1 descripcion
	FROM TMKK_TIP_VALOR
	WHERE (CTPV_COD_TIP_VALOR = @i_TIP_ESTADO OR @i_TIP_ESTADO = '' OR @i_TIP_ESTADO IS NULL)
	AND (CTPV_TIP_VALOR = @i_TIP_VALOR OR @i_TIP_VALOR = '' OR @i_TIP_VALOR IS NULL)
	AND (STPV_DES_TIP_VALOR_1 LIKE '%' + @i_DESCRIPCION + '%' OR @i_DESCRIPCION = '' OR @i_DESCRIPCION IS NULL)
END

GO
/****** Object:  StoredProcedure [dbo].[PRMKK_INS_BOF_TIP_VALOR]    Script Date: 6/10/2026 23:10:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[PRMKK_INS_BOF_TIP_VALOR]
    @i_CTPV_COD_TIP_VALOR   VARCHAR(20),
    @i_CTPV_TIP_VALOR       VARCHAR(8),
    @i_STPV_DES_TIP_VALOR_1 VARCHAR(128),
    @i_STPV_DES_TIP_VALOR_2 VARCHAR(128),
    @i_STPV_DES_TIP_VALOR_3 VARCHAR(128),
    @i_AUD_INS_USER         VARCHAR(16),
    @o_resultMessage        VARCHAR(500) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        INSERT INTO TMKK_TIP_VALOR(
            CTPV_COD_TIP_VALOR,
            CTPV_TIP_VALOR,
            STPV_DES_TIP_VALOR_1,
            STPV_DES_TIP_VALOR_2,
            STPV_DES_TIP_VALOR_3,
            AUD_INS_USER
        )
        VALUES (
            @i_CTPV_COD_TIP_VALOR,
            @i_CTPV_TIP_VALOR,
            @i_STPV_DES_TIP_VALOR_1,
            @i_STPV_DES_TIP_VALOR_2,
            @i_STPV_DES_TIP_VALOR_3,
            @i_AUD_INS_USER
        );

        COMMIT TRANSACTION;

        SET @o_resultMessage = '1|Registro correcto';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION;

        SET @o_resultMessage = '0|error en el procesamiento ' + ISNULL(ERROR_MESSAGE(), 'Error desconocido');
        -- Optionally: RETURN or rethrow. Current behavior returns via output parameter.
    END CATCH;
END
GO
/****** Object:  StoredProcedure [dbo].[PRMKK_UPD_BOF_EST_TIP_VALOR]    Script Date: 6/10/2026 23:10:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[PRMKK_UPD_BOF_EST_TIP_VALOR]
    @i_CTPV_COD_TIP_VALOR VARCHAR(20),  
    @i_CTPV_TIP_VALOR     VARCHAR(8),   
    @i_FTPV_ESTADO        VARCHAR(10),  
    @o_resultMessage      VARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        UPDATE TMKK_TIP_VALOR
        SET FTPV_ESTADO = @i_FTPV_ESTADO
        WHERE CTPV_COD_TIP_VALOR = @i_CTPV_COD_TIP_VALOR
        AND CTPV_TIP_VALOR = @i_CTPV_TIP_VALOR

        IF @@ROWCOUNT = 0
        BEGIN
            ROLLBACK TRANSACTION;
            SET @o_resultMessage = '0|Registro no encontrado';
            RETURN;
        END

        COMMIT TRANSACTION;
        SET @o_resultMessage = '1|Anulación correcta';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION;

        SET @o_resultMessage = '0|error en el procesamiento ' + ISNULL(ERROR_MESSAGE(), 'Error desconocido');
    END CATCH;
END

GO
/****** Object:  StoredProcedure [dbo].[PRMKK_UPD_BOF_TIP_VALOR]    Script Date: 6/10/2026 23:10:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[PRMKK_UPD_BOF_TIP_VALOR]
    @i_CTPV_COD_TIP_VALOR   VARCHAR(20),       -- key
    @i_CTPV_TIP_VALOR       VARCHAR(8)   = NULL,
    @i_STPV_DES_TIP_VALOR_1 VARCHAR(128) = NULL,
    @i_STPV_DES_TIP_VALOR_2 VARCHAR(128) = NULL,
    @i_STPV_DES_TIP_VALOR_3 VARCHAR(128) = NULL,
    @i_AUD_UPD_USER         VARCHAR(16)  = NULL,
    @o_resultMessage        VARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        UPDATE TMKK_TIP_VALOR
        SET
            CTPV_TIP_VALOR       = @i_CTPV_TIP_VALOR,
            STPV_DES_TIP_VALOR_1 = @i_STPV_DES_TIP_VALOR_1,
            STPV_DES_TIP_VALOR_2 = @i_STPV_DES_TIP_VALOR_2,
            STPV_DES_TIP_VALOR_3 = @i_STPV_DES_TIP_VALOR_3,
            AUD_INS_USER         = @i_AUD_UPD_USER
        WHERE CTPV_COD_TIP_VALOR = @i_CTPV_COD_TIP_VALOR
        AND CTPV_COD_TIP_VALOR = @i_CTPV_TIP_VALOR

        IF @@ROWCOUNT = 0
        BEGIN
            ROLLBACK TRANSACTION;
            SET @o_resultMessage = '0|Registro no encontrado';
            RETURN;
        END

        COMMIT TRANSACTION;
        SET @o_resultMessage = '1|Actualización correcta';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION;

        SET @o_resultMessage = '0|error en el procesamiento ' + ISNULL(ERROR_MESSAGE(), 'Error desconocido');
        -- Optionally return an error code after setting output
    END CATCH;
END

GO
